name: Beatbench
description: An almost DAW written in Dart.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  meta: ^1.1.8
  csslib: ^0.16.1
  async: ^2.4.2

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
